# Site information
site_name: THOTH Documentation Test
site_url: https://sitename.example
site_author: Stelios Alvanos
site_description: THOTH Documentation

# Copyright
# copyright: Copyright &copy; 2025 Stelios Alvanos

# Repository
repo_name: thoth-documentation-test
repo_url: https://github.com/Xenobii/thoth-documentation-test

# Config
theme:
  name: material
  palette:
    scheme: slate
    primary: grey
  logo: .../assets/thoth-logo.png
  favicon: .../assets/thoth-logo.png

# Extra
extra:
  social: 
    - icon: fontawesome/brands/github
      link: https://github.com/Xenobii

extra_css:
  - stylesheets/extra.css

# Page
nav:
  - Deployment: 
    - Basic Installation        : deployment/installation_basic.md
    - Advanced Installation     : deployment/installation_advanced.md
    - Opening a scene with THOTH: deployment/open_scene.md

  - Manual:
    - User Interface   : manual/ui.md
    - Tools            : manual/tools.md
    - Layers           : manual/layers.md
    - History          : manual/history.md
    - Viewpoints       : manual/viewpoint.md
    - Keybinds         : manual/keybinds.md
    - Collaborative    : manual/collab.md
    - Exporting changes: manual/export.md
    
  - API:
    - Events  : api/events.md
    - REST API: api/rest.md